#ifndef STM32_DFU_BOOTLOADER_LIB_GLOBAL_H
#define STM32_DFU_BOOTLOADER_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STM32_DFU_BOOTLOADER_LIB_LIBRARY)
#  define STM32_DFU_BOOTLOADER_LIB_EXPORT Q_DECL_EXPORT
#else
#  define STM32_DFU_BOOTLOADER_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif // STM32_DFU_BOOTLOADER_LIB_GLOBAL_H
